add task lesson3
AlexFrost1996/Test-Guru pull request #2
Opened 2021-09-10 15:35 UTC by AlexFrost1996

2021-09-10 17:54 UTC, BubuntuClu requested changes

2021-09-10 17:54 UTC, BubuntuClu commented on db/migrate/20210910151229_create_answers.rb
> +      t.integer :question_id
это должен быть внешний ключ

2021-09-10 17:54 UTC, BubuntuClu commented on db/migrate/20210910150101_create_questions.rb
> +      t.integer :test_id
это должен быть внешний ключ

2021-09-10 17:54 UTC, BubuntuClu commented on db/migrate/20210910115733_create_tests.rb
> +
тесты должны иметь внешний ключ к категориям
`t.references :category, foreign_key: true`

2021-09-10 19:49 UTC, AlexFrost1996 commented on db/migrate/20210910151229_create_answers.rb
> +      t.integer :question_id
Исправил

2021-09-10 19:49 UTC, AlexFrost1996 commented on db/migrate/20210910115733_create_tests.rb
> +
Исправил

2021-09-10 19:49 UTC, AlexFrost1996 commented on db/migrate/20210910150101_create_questions.rb
> +      t.integer :test_id
Исправил

2021-09-11 18:26 UTC, BubuntuClu requested changes

2021-09-11 18:26 UTC, BubuntuClu commented on db/migrate/20210910150101_create_questions.rb
> +      t.references :test_id, foreign_key: true
параметром для референса надо указать имя таблицы в единственном числе. ты указал имя колонки из-за чего имя сгенерилось `t.integer "test_id_id"`(в schema.rb ты можешь смотреть результат своих миграций)

2021-09-11 18:26 UTC, BubuntuClu commented on db/migrate/20210910151229_create_answers.rb
> +      t.references :question_id, foreign_key: true
тоже самое про параметр

2021-09-11 18:26 UTC, BubuntuClu commented on db/migrate/20210910151229_create_answers.rb
> +      t.references :user, foreign_key: true
это не потребуется, можешь удалить

2021-09-11 21:31 UTC, AlexFrost1996 commented on db/migrate/20210910150101_create_questions.rb
> +      t.references :test_id, foreign_key: true
Исправил, удалил id.

2021-09-11 21:32 UTC, AlexFrost1996 commented on db/migrate/20210910151229_create_answers.rb
> +      t.references :question_id, foreign_key: true
также удалил id.

2021-09-11 21:33 UTC, AlexFrost1996 commented on db/migrate/20210910151229_create_answers.rb
> +      t.references :user, foreign_key: true
удалил

2021-09-13 12:28 UTC, merged